### ISSUE TITLE
Organizing Your Projects

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#1]
**Chore summary**
- Write a guide to prevent the user from feeling lost or unaware of how to organize their project(s). 

**Tasks**
-  Explain how stoplight processes projects being brought in i.e API files, models, articles
-  Explain different ways to organize their projects that they are bringing into stoplight:
    - How many APIs in a repo (Single or Multiple)
    - Design + docs in the same repo
    - Design + docs in the same repo as implementation
    - Just docs
- Link to stoplight config for additional settings

**Additional context**
Importing a project would be a separate article linking to this.

**Comment by philsturgeon** [comment]
https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/01-working-with-projects.md

https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/02-working-with-files.md

**Comment by LukasRos** [comment]
I've already worked on this (esp. second bullet about repo organization): https://docs.google.com/document/d/1h_jbZi7YtjV4Iek7fQcQjgfmUXFKpBo8kPi7KQE5WTc/edit

**Comment by philsturgeon** [comment]
https://www.gatsbyjs.org/docs/gatsby-project-structure/

**Comment by philsturgeon** [comment]
@LukasRos thank you! I'll use this as a base for my PR.
