### ISSUE TITLE
Shared parameters and responses

### ISSUE THREAD

**Issue by lottamus** [stoplightio/platform-docs#106]
Let's add some docs on the "why" and "how" for using shared parameters and responses in Studio. Here's what we said in NEXT: https://docs.stoplight.io/modeling/modeling-with-openapi/shared-parameters-and-responses

![image](https://user-images.githubusercontent.com/7423098/101184237-19810b80-3616-11eb-95b6-b5ce552a9afb.png)

![image](https://user-images.githubusercontent.com/7423098/101184250-200f8300-3616-11eb-8c55-03512757f5c3.png)

**Comment by philsturgeon** [comment]
@lottamus I had a go at this, we need it for the newsletter. Can you review it, and improve it later if it needs more work?
