### ISSUE TITLE
Creating a design library

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#14]
**Chore summary**
Introduce design libraries, their benefits and how to create them.

**Tasks**
- Why?
- When to use?
- How to create?
- Evangelising their need to api architects

**Comment by philsturgeon** [comment]
https://docs.google.com/document/d/1k7VtOScK6mqnUOsQRE2GSZq65m3JEbxg9WOCvnvThaU/edit#

**Comment by LukasRos** [comment]
I'm working on adapting the Google doc I wrote to the new docs format.

**Comment by LukasRos** [comment]
I now talk about consistency on micro and macro level. For the micro level, this might be connected somehow to Spectral validation.
