### ISSUE TITLE
Shared Style Guide UI text assistance

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/platform-docs#149]
Figma links:

https://www.figma.com/file/kqP4TRrPy6ZsNVpilshTQs/Style-Guides-Screens?node-id=579%3A42260

https://www.figma.com/file/ElykPWsMYrHducaohDJ6cV/Studio?node-id=2021%3A69914

**Comment by pamgoodrich** [comment]
@noor-ahmad : 

Here is some text for the main Styles Guide page: 

- Automatic standards enforcement
- Share across projects and groups
- Ready-to-use standards
- Custom rulesets and functions
- Easily publish errors and responses

Here is some text for the Given and Then hovers:

*Given* - Selects the part of the document to apply rules to as a string or array of valid JSON Path Plus expressions.

*Then* - Explains which core or custom function to apply to the Given JSONPath.

Can you let Sydney and I know if these work for you?

**Comment by noor-ahmad** [comment]
@pamgoodrich @sydstoplight This looks good to me, thank you! Tagging @naumanali-stoplight just to confirm :)

**Comment by pamgoodrich** [comment]
Thanks, @noor-ahmad. I'll close this as completed, and we can adjust wording as needed through the dev cycle.
