### ISSUE TITLE
Starting a new API design

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#15]
**Chore summary**
Guide the API architect on the best way to go about creating a new API

**Tasks**
- Do API Design first
- Get quick feedback
- Look for redundancy in the explorer
- Look for components that can be reused
- Make sure standards are being followed. Check for warning, errors 
- Plan documentation (Pointers for tech writers)

**Comment by philsturgeon** [comment]
https://stoplight.io/blog/getting-started-with-api-design-using-stoplight-and-openapi-90fc8f37ac2e/

**Comment by mnaumanali94** [comment]
I can convert this blog into a quick start guide.

**Comment by philsturgeon** [comment]
I have started a thing hold off for now.

**Comment by philsturgeon** [comment]
Ok I kicked things off over here https://github.com/stoplightio/platform-docs/pull/21 

@mnaumanali94 would you take over, updating that blog post and keeping it high level without getting tooooo stuck into OpenAPI?

**Comment by mnaumanali94** [comment]
I will.
