### ISSUE TITLE
Default Structure question

### ISSUE THREAD

**Issue by melissahughesatx** [stoplightio/platform-docs#194]
Is it worth noting in the docs that in order for the default structure to apply to published live docs the TOC is required?

**Comment by melissahughesatx** [comment]
https://meta.stoplight.io/docs/platform/ZG9jOjIxOTkxNTkz-project-sidebar

**Comment by pamgoodrich** [comment]
@ryotrellim: I think we determined that this is a software bug and not a doc issue. Can you confirm and let me know if I can close it? Or, if there is something I need to add to the doc to support this customer's issue, let me know and I'll use this issue to do that.

**Comment by ryotrellim** [comment]
Reviewed the [thread](https://stoplight-internal.slack.com/archives/CELPZGMA4/p1637704632318900) and it looks like it's a bug. Closing!
