### ISSUE TITLE
Ideas: Something about Security?

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/platform-docs#20]
How to manage security in studio https://stoplight.io/blog/api-security-in-openapi-b105ae725a08/ 

then how that effects your mocks and generally how it fits in with APIs

**Comment by LukasRos** [comment]
Might be something for me to work on since I wrote that original blog post.

**Comment by philsturgeon** [comment]
Spoke to @mnaumanali94 today and I think this would better off covered in the Studio documentation instead of this platform docs repo. If you'd like to work on it over there, with updated screenshots and covering all of the auth types in OAS3, that would be very appreciated.

**Comment by mnaumanali94** [comment]
@LukasRos

**Comment by LukasRos** [comment]
@philsturgeon Can you point me where exactly you want those docs to live and how I can contribute there?

**Comment by philsturgeon** [comment]
@LukasRos https://github.com/stoplightio/studio/tree/master/docs

**Comment by LukasRos** [comment]
Created and PR submitted: https://github.com/stoplightio/studio/pull/393

**Comment by philsturgeon** [comment]
Awesome @LukasRos, sorry for the delay. I'll review it.
