### ISSUE TITLE
Document scopes for each OAuth App

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/platform-docs#220]
From Chelsea:
I was just talking about this the other day, we should get this documented at some point. @Pam Goodrich maybe you can add it to your backlog to document the scopes needed for each provider OAuth App?

https://stoplight-internal.slack.com/archives/C0258SZH9SB/p1639689563207500

https://stoplight-internal.slack.com/archives/CN2781QQZ/p1639514011327900

https://meta.stoplight.io/docs/platform/ZG9jOjQ0MzM3Mg-git-lab

**Comment by pamgoodrich** [comment]
@chohmann : I think I have the GitLab scope, but not the others. Do you know if this information is documented somewhere internally? If not, who can provide it to me?

**Comment by chohmann** [comment]
1. GitHub --> Enablers can look up the scopes that are set for our Production GitHub.com OAuth App
2. BitBucket Server --> N/A, does not support OAuth
3. BitBucket Cloud --> Enablers can look up the scopes that are set for our Production Bitbucket.org OAuth App
4. Azure Devops Server -->N/A, does not support OAuth
5. GitLab --> you already have it

**Comment by ryotrellim** [comment]
Some more troubleshooting steps in this thread that might be worth documenting: https://stoplight-internal.slack.com/archives/C0258SZH9SB/p1641917368021300
