### ISSUE TITLE
Ideas: Governance section - Style guides

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#23]
While Spectral is well documented in its docs. An article about common rules to make when creating a style guide. What factors to take into account like what your current landscape is. Maybe starting with warnings, and enforcing stricter rules as it progresses. This can also point towards `Quality` a feature that is coming soon.  @philsturgeon

**Comment by philsturgeon** [comment]
@mnaumanali94 how much of this is useful? https://www.apisyouwonthate.com/blog/automated-style-guides-for-rest-graphql-and-grpc/

@lottamus is there an ability for studio web to use workspace-wide spectral rules yet? Is that possible for Studio Desktop?

**Comment by mnaumanali94** [comment]
@philsturgeon This helps.I'd say we use some the content there, but primarily come up with some rules that a user can potentially use. Like a reference rule set in the form of an article. https://github.com/openapi-contrib/style-guides/blob/master/openapi.yml Maybe this to start with and some additions.

**Comment by philsturgeon** [comment]
Done in https://github.com/stoplightio/platform-docs/blob/master/docs/2.-governance/e.style-guides.md
