### ISSUE TITLE
Document supported browser and versions

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/platform-docs#25]
We should document supported browsers by different parts of the platform (hubs, studio, etc). Some customers require support of IE11 for their documentation, for example. We should document browsers that we do not support.

**Comment by philsturgeon** [comment]
@lottamus can I copy the answers off of you?

**Comment by philsturgeon** [comment]
@marbemac can we confirm if we're going to drop support for Safari so we can document this?

**Comment by dgrstl** [comment]
@rossmcdonald We also need to document supported k8s distributions.

**Comment by rossmcdonald** [comment]
@dgrstl That's more in line with #30. I've updated the description to reflect this.

**Comment by marbemac** [comment]
Ok based on the data from last year's worth of Next Hubs visits here's what I suggest:

|               | Chrome | Safari                   | Firefox | Edge                     |
|---------------|--------|--------------------------|---------|--------------------------|
| Elements/Docs | 68     | 12                       | 60      | 18                       |
| Platform      | 68     | 12                       | 60      | Not Officially Supported |
| Studio        | 75     | Not Supported | 68      | Not Supported |

I do not suggest that everything works perfectly at these targets - we need to verify. This is just the suggested goal. Edge 18 is the biggest wildcard, as it sounds like it's currently not working. After investigating, if it is a lot of work to support, we'll need to access our options.

Next step would be for somebody to spin up browser stack and start investigating what it would take to get docs rendering in Edge 18 (as well as just verify the rest of the targets above).
