### ISSUE TITLE
Missing redirect - Tags

### ISSUE THREAD

**Issue by ryotrellim** [stoplightio/platform-docs#259]
Conversation: https://stoplight-internal.slack.com/archives/CELPZGMA4/p1644260787501409

Old page: https://meta.stoplight.io/docs/platform/ZG9jOjU4NzU5Mw-quality-api-reference-documentation#tags
New page(?): https://meta.stoplight.io/docs/api-best-practices/ZG9jOjM2NTM5Nzc1-quality-api-reference-documentation#tags

**Comment by pamgoodrich** [comment]
@ryotrellim : I don't think we can use redirects on meta because we are not using a custom domain. I'm not sure how we solve this for topics that have been moved. Do you or @mnaumanali94 have some ideas?

**Comment by mnaumanali94** [comment]
@stoplightio/enablers is there a way we can get a custom domain for meta. Same domain but for platform to just recognize it as a custom domain 🤔

**Comment by pamgoodrich** [comment]
@mnaumanali94: It looks like someone added some redirects for meta, but they don't work. @stoplight/enablers: can someone take a look?

**Comment by pamgoodrich** [comment]
We do not have a way to provide redirects on meta at this time. For now, our approach is to work with stakeholders to manually change links when we move files.
