### ISSUE TITLE
Document URL IDs

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/platform-docs#266]
What are these, how are these generated, and can they be changed?

![image.png](https://images.zenhubusercontent.com/615c69349dea84b3f80ac045/462ae47c-976e-4e6e-82c6-d096384fbbe0)

It looks like the ID might change if you change the topic title, but I'm not 100% sure about that.

Bill Burch:
That would be helpful.  We do get quite a few questions on this topic and it would be great to provide some insight.  One of the biggest issues customer run into is trying to send a link externally and it not working.  Understanding the ID's and how to utilize them would be helpful.

**Comment by pamgoodrich** [comment]
@mnaumanali94 : Bill says you have helped support with this in the past. Do you have information you can add to this issue?

**Comment by mnaumanali94** [comment]
They are permalinks, generated based on the location of the file. They can't be changed by the User and are stable unless location of file changes. These slack convos should be a good starting context.

Slack Convo: https://stoplight-internal.slack.com/archives/CELPZGMA4/p1629402637187600?thread_ts=1629402235.187400&cid=CELPZGMA4
Slack Convo: https://stoplight-internal.slack.com/archives/CELPZGMA4/p1643057626171700

**Comment by pamgoodrich** [comment]
@mnaumanali94 : Do the permalinks need to be added to redirects? If so, we should update this article at the same time: https://meta.stoplight.io/docs/platform/ZG9jOjE2OTE5OTUx-redirects

Let me know.
