### ISSUE TITLE
Connecting to VCS

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#3]
**Chore summary**
Write a guide to help a user connect their VCS of choice to platform

**Tasks**
- Importance of setting up VCS
- Quick start for default integrations
- How to set up a VCS integration
   - GitHub
   - GitLab

**Comment by philsturgeon** [comment]
@lottamus this was a little tricky in v2-demo as the GitHub app UI looks different to the demo. Is it out of date, or is it a configuration thing?

**Comment by lottamus** [comment]
@mnaumanali94 @philsturgeon most Workspaces in SaaS won't need to configure any integrations. Every new Workspace will come pre-installed with Github, Gitlab, and Bitbucket Cloud. If a Workspace needs a different integration or wants to configure their own Github/Gitlab/Bitbucket cloud application, they will be able to do so view the Workspace Integration's screen

![image](https://user-images.githubusercontent.com/7423098/78105816-a43ea600-73b7-11ea-8c93-1baeafe784cc.png)

By default, Stoplight's Github app will be installed

![image](https://user-images.githubusercontent.com/7423098/78105844-b882a300-73b7-11ea-8949-44f3a875be2e.png)

Workspace's can optionally configure their own Github app

![image](https://user-images.githubusercontent.com/7423098/78105882-d2bc8100-73b7-11ea-8a3d-7954d823f4b6.png)

Workspace members will be able to connect any of the installed Workspace Integrations via the Connected Accounts screen

![image](https://user-images.githubusercontent.com/7423098/78105953-00a1c580-73b8-11ea-973b-dd51a514eb99.png)

**Comment by mnaumanali94** [comment]
@lottamus Thanks for the pointers. This section "Setting up workspaces" of the documentation aims to guide the user step by step to the point of having their projects in the platform and proceeding with inviting collaborators. For anybody using the default settings they wouldn't have to read the whole doc. People with advanced use cases can use it to set up their VCS. I wouldn't want this to be somewhere in an advanced section as this can be a blocker.

**Comment by philsturgeon** [comment]
Yeah we can say "You'll have these set up by default, and if you want to get creative you can do X Y Z" pretty early on. We can give folks a "next page"· escape hatch without forcing them to read the "configure your own bitbucket server or whatever" content
