### ISSUE TITLE
Publish projects via CLI

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#32]
**Chore summary**
Create a guide to publishing projects via CLI

**Tasks**
@philsturgeon Do you think its a good idea to write a concise guide and make it a section in the `adding projects` article. I don't think it warrants for a separate article.

**Comment by philsturgeon** [comment]
Yeah I think this should be a small mention in some other article, like we've already done mentioning git-based or cli-based projects.

This has its own page in Studio, and I think it should be moved to its own page in Platform when we start having more "How" contents. This doesnt make sense as a "Guide".

**Comment by philsturgeon** [comment]
Agggh no I think we could probably do a guide.

Quickly overview why and when folks might want to do this (some code first holdouts or you're using Bazaaaar or MS Source Safe...), explain its read only, nobody can use Studio to edit things, etc. 

We want to be able to link people to this page if they have concerns about not wanting to use git.

**Comment by mnaumanali94** [comment]
Add that to the section in "Adding projects" maybe? This case would probably be most useful for people getting started. They might have git but don't want to use it yet. The goal being the adding projects guide gets them started either way. 

Would we also want to write something about how to organize their projects in this case? Or the monorepo vs multirepo approach still apply?

**Comment by philsturgeon** [comment]
I dont think git vs CLI makes much difference to organization. Git is just analyzing according the stoplight config, cli is analyzing according to the stoplight config.
