### ISSUE TITLE
Stoplight config

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/platform-docs#4]
**Chore summary**
Help people tweak how their project is processed by the platform.

**Tasks**
- What is the stoplight config?
- Where do you place the stoplight config?
- What can you do with it? 
- Any best practices?

**Additional context**
If we have existing documentation we can port it over here.

**Comment by philsturgeon** [comment]
Relevant content in https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/03-stoplight-config.md
