### ISSUE TITLE
Documentation for configuring integrations

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/platform-docs#51]
We need a doc both for providing an overview of what an integration is as well as how to configure them:

- [ ] Gitea
- [ ] Bitbucket Cloud
- [ ] Bitbucket Server
- [ ] Github
- [ ] GitLab
- [ ] LDAP
- [ ] SAML

And soon to be added:

- [ ] Azure DevOps

**Comment by philsturgeon** [comment]
@mnaumanali94 bump 😋

**Comment by mnaumanali94** [comment]
Closed by #71
