### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/platform-docs#54]
**Chore summary**

How table of contents works for articles, endpoints, apis, models, etc

**Additional context**

ToC is auto guessed from folder names, file name or frontmatter, tags for grouping things (in frontmatter and also OAS tags), and for custom ordering the "workaround" with numbers.

**Comment by philsturgeon** [comment]
Show how models and operations are split up. Currently they are squished together but they are being separated. https://github.com/stoplightio/platform-internal/issues/2603

**Comment by lottamus** [comment]
We've got a description of how the default TOC is implemented here too: https://github.com/stoplightio/platform-internal/issues/3206
