### ISSUE TITLE
Unsubscribe link in new workspace drip campaign is broken

### ISSUE THREAD

**Issue by dgrstl** [stoplightio/platform-docs#63]
Example email is attached, the link the unsubscribe takes you is https://hs-4892910.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?d=Vnbsh-7GHZ4zVzn02n4cQhLFW3ZWVhl4fdJvhMX6jfV4chTYVQtCz36bt6nWN5LBGQcCzHlyW8M_tqy6MnxSbW98R2C36pFPx9V1yf0N30NwcjW3c3_l07gFTWMW8dw3qS4Jj4VL2483&v=3&utm_campaign=v2%20Launch&utm_source=hs_automation&utm_medium=email&utm_content=89225665&_hsenc=p2ANqtz--T4L3yS4tbtaLCRJ_vDy9jjFVWT9U7Eh75MABdAH8W7hQ0yj4BeBTALZv-GIzUduQj9NeTEwdde8okLv8ZJkZdWHH-6g&_hsmi=89225665

And the resulting screen looks like this
<img width="1905" alt="2020-06-26_13-47-59" src="https://user-images.githubusercontent.com/2438381/85906382-c6d43580-b7d3-11ea-8f94-3e799fc62779.png">

**Comment by ksatx** [comment]
I don't have the permissions to close this issue, but these are sent from Hubspot and don't have anything to do with the contents of this repo. I'll look into it.

**Comment by ksatx** [comment]
Should be fixed now - 

![image](https://user-images.githubusercontent.com/51092436/86032144-80adea80-b9fc-11ea-9460-b9cf1a263cd0.png)
**
![image](https://user-images.githubusercontent.com/51092436/86032159-84da0800-b9fc-11ea-96cc-88c4ef8f5af3.png)
**

**Comment by dgrstl** [comment]
Thanks!
