### ISSUE TITLE
Branch Management

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/platform-docs#64]
How does branch management work in general

Changing your default branch

Difference between default and visible

What does visible mean to studio, explorer, docs, etc.

what sort of use cases (like v1 and v2 branches for versioning, or master / develop branches for git flow type users, etc)

@lottamus i think a brain dump from you could get us started here and we can turn that into docs.

**Comment by philsturgeon** [comment]
@lottamus I think branch management is now ready to go on prod? Generally available? Can we get that brain dump for docs or you do a run through showing it off?

**Comment by lottamus** [comment]
@philsturgeon yeah it's generally available now

The docs sidebar will now show a versions dropdown if there are multiple branches being tracked for a Git project. Explorer **only** shows the default branch and does not have the versions dropdown.

There are two types of branches shown in the versions dropdown:
- Published branches (called "Versions") are viewable to everyone including guests and viewer roles
- Unpublished branches are only viewable to workspace makers, admins, and owners.

![image](https://user-images.githubusercontent.com/7423098/87461022-661a6a80-c5d3-11ea-96cf-4215805fc22a.png)


From the project settings screen, project admins are able to:
- track branches
- change default branch
- publish branches
- rename branches
- remove branches

### Track Branch

- Freeform input to enter the name of an **existing** Git branch to track
- Tracking a Git branch will analyze it and add it to your list of branches
- Does **not** allow you to create new Git branches

![image](https://user-images.githubusercontent.com/7423098/87463573-438a5080-c5d7-11ea-9d2a-468799eaf45e.png)

### Default Branch

- Shown by default in Docs and Explorer
- Cannot be unpublished or removed. If you need to do either of these, please select another default branch first.

### Publish Branch

- Shows branch in the Versions dropdown for guests and viewers

![image](https://user-images.githubusercontent.com/7423098/87461327-e3de7600-c5d3-11ea-8d0c-1d61cf2e6c0b.png)

### Rename Branch

- Changes the name that's viewed in the Versions dropdown
- Does **not** change the underlying Git branch's name

### Remove Branch

- Removes the branch from Stoplight
- Does **not** remove the Git branch

![image](https://user-images.githubusercontent.com/7423098/87464217-5cdfcc80-c5d8-11ea-8ecd-ede07b4b222e.png)
