### ISSUE TITLE
SAML Setup Instructions

### ISSUE THREAD

**Issue by stephenlprice** [stoplightio/platform-docs#67]
As a Platform Admin I would like to setup SAML for Stoplight, however I cannot find any docs describing what this process would look like and I get stuck.

## Is your feature request related to a problem?

I am frustrated by not being able to setup SAML correctly and now I need to engage Stoplight's support team for assistance.

## Describe the solution you'd like

Add an article to our platform documentation that explains how to successfully integrate with one sample SAML provider such as Okta. I was able to do so by following the steps described in Swagger's docs and using an Okta dev account: https://app.swaggerhub.com/help/enterprise/user-management/sso/okta

Eventually I think it would be great to have a dedicated section for Stoplight Admins letting them know how to setup their workspace for success.

## Additional context

Issue raised by a new customer: GHX -> [ticket #2249](https://stoplight.zendesk.com/agent/tickets/2249).

**Comment by mnaumanali94** [comment]
Closed by #71
