### ISSUE TITLE
BitBucket Server Integration Steps

### ISSUE THREAD

**Issue by stephenlprice** [stoplightio/platform-docs#68]
As a Platform Admin I would like to setup a BitBucket Server integration for Stoplight, however I cannot find any docs describing what this process would look like and I get stuck.

## Is your feature request related to a problem?

I am frustrated by not being able to use GIT correctly, thus slowing down my evaluation and now I need to engage Stoplight's support team for assistance.

## Describe the solution you'd like

Add an article to our platform documentation that explains how to successfully integrate with BitBucker Server, similar to what we have for V1: https://support.stoplight.io/hc/en-us/articles/360035146451-Configuring-Bitbucket-Server

## Additional context

Issue raised by a new customer: GHX -> [ticket #2249](https://stoplight.zendesk.com/agent/tickets/2249).

**Comment by mnaumanali94** [comment]
Closed by #71
