### ISSUE TITLE
Update migration guides with steps to cancel accounts in legacy systems

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/platform-docs#70]
Users will need to cancel and then re-subscribe.

- [ ] Next
- [ ] Classic

**Comment by philsturgeon** [comment]
@rossmcdonald how _do_ users cancel their next account? 

<img width="776" alt="image" src="https://user-images.githubusercontent.com/67381/89788009-634d5f80-db16-11ea-8e29-39c31215c59d.png">

**Comment by rossmcdonald** [comment]
There's an option under your account settings:

https://next.stoplight.io/profile

![image](https://user-images.githubusercontent.com/4060903/89909326-90504f80-dbb4-11ea-89f5-6abf1021727a.png)

I don't believe it's documented anywhere, so googling won't help.
