### ISSUE TITLE
Adding Git Credentials in Studio Desktop v2

### ISSUE THREAD

**Issue by lottamus** [stoplightio/platform-docs#83]
## Summary

In Studio Desktop v2, you no longer need to log into your Stoplight account to use the built in Git functionality. You can work with any VCS provider by adding your Git credentials for the matching VCS's host such as https://github.com.

## How to add credentials for Github

1. Create a new personal access token https://github.com/settings/tokens/new or follow the guide on Github: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

3. Choose "repo" permissions to allow enable read/writing files in your Git repository then generate the token.

![image](https://user-images.githubusercontent.com/7423098/89740366-8829d000-da4d-11ea-830f-a7aed60a9a65.png)

4. Open Studio Desktop's settings dialog and enter your Git credentials

<img width="1680" alt="Screen Shot 2020-08-09 at 2 48 38 PM" src="https://user-images.githubusercontent.com/7423098/89740586-ae506f80-da4f-11ea-98f2-9e71c917e5ab.png">

**Comment by philsturgeon** [comment]
Handled in the Studio repo with this PR https://github.com/stoplightio/platform-docs/issues/83
